# Titra - Create Developer Environment
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: titra-create-developer-env
  title: Titra - Create Developer Environment
  description: Self-service front end for Developer Environment Creation
  tags:
    - beta
    - demo
spec:
  owner: user:default/joseph.titra
  type: environment
  parameters:
    - title: Environment Details
      required:
        - new_app_name
      properties:
        cloud_provider:
          title: Select Cloud Environment
          type: string
          enum:
            - AWS
            - Azure
            - GCP
          ui:widget: radio
        new_app_name:
          title: Application Name
          type: string
          description: Unique name for your new application (max:14 characters)
          maxLength: 14
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(_[a-zA-Z0-9]+)*$'
      dependencies:
        cloud_provider:
          allOf:
            - if:
                properties:
                  cloud_provider:
                    const: AWS
              then:
                required:
                  - aws_instance
                properties:
                  aws_instance:
                    title: AWS Instance Type
                    type: string
                    description: Select the AWS Instance Type
                    enum:
                      - t2.micro
                      - t3.micro
                      - t3.small
            - if:
                properties:
                  cloud_provider:
                    const: Azure
              then:
                required:
                  - azure_instance
                properties:
                  azure_instance:
                    title: Azure Instance Type
                    type: string
                    description: Select the Azure Instance Type
                    enum:
                      - B1s
                      - B1ms
            - if:
                properties:
                  cloud_provider:
                    const: GCP
              then:
                required:
                  - gcp_instance
                properties:
                  gcp_instance:
                    title: GCP Instance Type
                    type: string
                    description: Select the GCP Instance Type
                    enum:
                      - f1-micro
                      - e2-micro
                      - e2-small
    - title: Application Details
      properties:
        deploy_application:
          title: Deploy Application
          description: Deploy application framework on newly provisioned environment (default:true)
          type: string
          enum:
            - true
            - false
          ui:widget: radio
          default: true
        application_type:
          title: Application Type
          type: string
          description: Application framework to configure (default:java)
          enum:
            - python
            - java
            - dotnet
            - none
          default: java
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Requesting Your New Environment
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/6_vVHzo9Qeu9fXvj-AcbCQ/module/iacm/orgs/SE_Sandbox/projects/Titra/pipelines/Create_Repo_and_Workspace/pipeline-studio?storeType=INLINE
        inputset:
          cloud_provider: ${{ parameters.cloud_provider }}
          new_app_name: ${{ parameters.new_app_name }}
          instance_type: ${{ parameters.aws_instance if parameters.aws_instance else none }}
          deploy_application: ${{ parameters.deploy_application }}
          application_type: ${{ parameters.application_type }}
          requestor_name: ${{ user.entity.metadata.name }}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
