apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: provision-react-app
  title: Provision a New React Application
  description: Creates a new React service using standardized application patterns
  icon: nodejs
  tags:
    - react
spec:
  owner: joseph.titra@harness.io
  type: service
  parameters:
    - title: Provide details for the application you want to create
      required:
        - app_name
        - app_description
      properties:
        app_name:
          title: Application Name
          type: string
          description: Name of the application
        app_description:
          title: Description of the new Application
          type: string
          description: Description of the application
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Provision a New Application
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/EeRjnXTnS4GrLG5VNNJZUw/all/orgs/sandbox/projects/Titra/pipelines/Onboard_React_Application/pipeline-studio?storeType=INLINE
        inputset:
          app_name: ${{ parameters.app_name }}
          app_description: ${{ parameters.app_description }}
          app_owner: ${{ user.entity.spec.profile.email }}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
