# SE - Sandbox Environment Creation
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sandbox_env_creation
  title: Titra - Sandbox Environment Creation
  description: Self-service front end offering for short-lived sandbox environments
  tags:
    - beta
    - hidden
spec:
  owner: user:default/joseph.titra
  type: environment
  parameters:
    - title: Environment Details
      required:
        - harness_project
        - cluster_name
      properties:
        harness_project:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: Harness Project
            description: Pick one of the Harness projects you are an Admin of.
            placeholder: "Choose a Harness Project"
            path: proxy/project-admin/user_admin_projects?user_email=${{ user.entity.spec.profile.email }}
            valueSelector: admin_projects
        cloud_provider:
          title: Select Cloud Environment
          type: string
          enum:
            - GCP
            - Azure
            - AWS
          ui:widget: radio
        cluster_name:
          title: K8s Cluster Name
          type: string
          description: Unique name for new K8s cluster (max:18 characters)
          maxLength: 18
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
    - title: Cluster Details
      properties:
        control_plane_nodes:
          title: Control Plane Nodes
          type: number
          description: Number of control plane nodes (default:1)
          default: 1
        ingress_type:
          title: Ingress Type
          type: string
          description: Type of ingress controller (default:ngnix)
          enum:
            - ngnix
            - istio
          default: ngnix
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
  steps:
    - id: trigger
      name: Requesting Your New Environment
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/EeRjnXTnS4GrLG5VNNJZUw/all/orgs/sandbox/projects/Titra/pipelines/Global_Payments_IaCM_Demo/pipeline-studio/?storeType=INLINE
        inputset:
          cloud_provider: ${{ parameters.cloud_provider }}
          cluster_name: ${{ parameters.cluster_name }}
          requestor_name: ${{ user.entity.metadata.name }}
        apikey: ${{ parameters.token }}
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
